name: Typescript-build

on: [push, pull_request]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        uses: ./.github/workflows/install-deps.yml
      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: upload-node-modules
          path: node_modules

  build:
    needs: install-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    name: Node ${{ matrix.node }}
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: download node_modules
        uses: actions/download-artifact@v4
        with:
          name: upload-node-modules
      - name: Build
        run: yarn build
