name: Typescript-build

on: [push, pull_request]

jobs:
  build:
    needs: install-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    name: Node ${{ matrix.node }}
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install Dependencies
        uses: ./.github/workflows/install-deps.yml
      - name: Build
        run: yarn build
