name: Typescript-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      
      - name: Install Dependencies
        uses: ./.github/actions/install-deps.yml
      - name: Build
        run: yarn build
