name: Typescript-build

on: [push, pull_request]

jobs:
  install-deps:
    uses: ./.github/workflows/install-deps.yml

  build:
    needs: install-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    name: Node ${{ matrix.node }}
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: yarn build
